# Imports and Settings

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None

# PR2 Data Path

In [3]:
dataset = "./PR2/pr2_version_5.0.0_merged.xlsx"

# Load Data

In [4]:
raw = pd.read_excel(dataset)
raw.head()

,pr2_accession,domain,supergroup,division,subdivision,class,order,family,genus,species,genbank_accession,start,end,label,gene,organelle,reference_sequence,added_version,edited_version,edited_by,edited_remark,remark,taxo_id,taxo_edited_version,taxo_edited_by,taxo_remark,reference,mixoplankton,worms_id,worms_marine,worms_brackish,worms_freshwater,worms_terrestrial,seq_id,sequence,sequence_length,ambiguities,sequence_hash,gb_date,gb_division,gb_definition,gb_organism,gb_organelle,gb_taxonomy,gb_strain,gb_culture_collection,gb_clone,gb_isolate,gb_isolation_source,gb_specimen_voucher,gb_host,gb_collection_date,gb_environmental_sample,gb_country,gb_lat_lon,gb_collected_by,gb_note,gb_publication,gb_authors,gb_journal,eukref_name,eukref_source,eukref_env_material,eukref_env_biome,eukref_biotic_relationship,eukref_specific_host,eukref_geo_loc_name,eukref_notes,pr2_sample_type,pr2_sample_method,pr2_latitude,pr2_longitude,pr2_depth,pr2_ocean,pr2_sea,pr2_sea_lat,pr2_sea_lon,pr2_country,pr2_location,pr2_location_geoname,pr2_location_geotype,pr2_location_lat,pr2_location_lon,pr2_sequence_origin,metadata_remark,pr2_continent,pr2_country_geocode,pr2_country_lat,pr2_country_lon,eukribo_UniEuk_taxonomy_string,eukribo_V4,eukribo_V9,silva_taxonomy,organelle_code,sequence_label
0,AB012059.1.1450_U,Archaea,DPANN,Nanoarchaeaeota,Nanoarchaeaeota_X,Nanohaloarchaeia,Nanohaloarchaeales,Nanohaloarchaeaceae,Nanohaloarchaeaceae_X,Nanohaloarchaeaceae_X_sp.,AB012059,1,1450,U,16S_rRNA,NaN,NaN,4.14.0,NaN,D. Vaulot,NaN,Silva Seed 132-UncHa209,71988,4.14.0,D. Vaulot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549396,TCACTGCTATCGGAGTCCGATTTAGCCATGCTAGTCCACCGAGCCC...,1408,0,8423d72a3c945e61ba0f9b11383bbbb1df8233b1,08-SEP-1998,ENV,Uncultured haloarchaeon MSP41 gene for 16S rRN...,uncultured haloarchaeon MSP41,NaN,Archaea; Euryarchaeota; environmental samples,NaN,NaN,MSP41,SG-41,East African alkaline saltern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Novel archaeal phylotypes from an East African...,"Grant,S.","Extremophiles 3 (2), 139-145 (1999)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,environmental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,clone_MSP41
1,AB012050.1.1450_U,Archaea,DPANN,Nanoarchaeaeota,Nanoarchaeaeota_X,Nanohaloarchaeia,Nanohaloarchaeales,Nanohaloarchaeaceae,Nanohaloarchaeaceae_X,Nanohaloarchaeaceae_X_sp.,AB012050,1,1450,U,16S_rRNA,NaN,NaN,4.14.0,NaN,D. Vaulot,NaN,Silva Seed 132-UncHa210,71988,4.14.0,D. Vaulot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549397,TCACTGCTATCGGAGTCCGATTTAGCCATGCTAGTCCACCGAGCCC...,1408,0,c1bd2c6a77e8f45a37a23e00e22c5fd2cd4f94fd,08-SEP-1998,ENV,Uncultured haloarchaeon MSP8 gene for 16S rRNA...,uncultured haloarchaeon MSP8,NaN,Archaea; Euryarchaeota; environmental samples,NaN,NaN,MSP8,SG-8,East African alkaline saltern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Novel archaeal phylotypes from an East African...,"Grant,S.","Extremophiles 3 (2), 139-145 (1999)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,environmental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,clone_MSP8
2,AF068819.1.1419_U,Archaea,Methanoteca,Euryarchaeota,Euryarchaeota_X,Archaeoglobi,Archaeoglobales,Archaeoglobaceae,Archaeoglobaceae_X,Archaeoglobaceae_X_sp.,AF068819,1,1419,U,16S_rRNA,NaN,NaN,4.14.0,NaN,D. Vaulot,NaN,Silva Seed 132-UncA6843,71948,4.14.0,D. Vaulot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549277,CCGCTGCTATCCGGCTGGGACTAAGCCATGCTAGTCTAGGGGCTTG...,1416,2,48d550fb2e9e2872f37a82130baf12942ce6cb2d,02-JUN-1999,ENV,Uncultured archaeon VC2.1 Arc8 16S ribosomal R...,uncultured archaeon VC2.1 Arc8,NaN,Archaea; environmental samples,NaN,NaN,VC2.1_Arc8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,environmental archaeal DNA from vent cap,Novel bacterial and archaeal lineages from an ...,"Reysenbach,A.L.","Appl. Environ. Microbiol. 66 (9), 3798-3806 (2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,environmental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,clone_VC2.1_Arc8
3,AF419628.1.1456_U,Archaea,Methanoteca,Euryarchaeota,Euryarchaeota_X,Archaeoglobi,Archaeoglobales,Archaeoglobaceae,Archaeoglobaceae_X,Archaeoglobaceae_X_sp.,AF419628,1,1456,U,16S_rRNA,NaN,NaN,4.14.0,NaN,D. Vaulot,NaN,Silva Seed 132-UncAr239,71948,4.14.0,D. Vaulot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549280,CCGCTGCTATCTGGCTGAGACTAAGCCATGCTAGTCCAGGGGCTTG...,1416,4,71e5c30d371577f53560b28ae520dab6af838afa,01-DEC-2001,ENV,Uncultured archaeon GBa1r015 16S ribosomal RNA...,uncultured archaeon,NaN,Archaea; environmental samples,NaN,NaN,NaN,GBa1r015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0-1 cm core A,Microbial diversity of hydrothermal sediments ...,"Teske,A.","Appl. Environ. Microbiol. 68 (4), 1994-2007 (2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,environmental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,clone_
4,Y10011.1.1488_U,Archaea,Methanoteca,Euryarchaeota,Euryarchaeota_X,Archaeoglobi,Archaeoglobales,Archaeoglobaceae,Archaeoglobus,Archaeoglobus_sp.,Y10011,1,1488,U,16S_rRNA,NaN,NaN,4.14.0,NaN,D. Vaulot,NaN,Silva Seed 132-I4YVene2,71949,4.14.0,D. Vaulot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549306,CCGCTGCTATCCGGCTGGGACTAAGCCATGCNAGTCAAGGGGCTTG...,1420,3,c2318d75d3150f7ecb426856b3cce7d215e3f56d,31-MAR-1997,BCT,Archaeoglobus veneficus 16S rRNA gene (partial...,Archaeoglobus veneficus,NaN,Archaea; Euryarchaeota; Archaeoglobi; Archaeog...,SNP6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"internal transcribed spacer 1, ITS1",Bacterial origin for the isoprenoid biosynthes...,"Boucher,Y.","Mol. Biol. Evol. 18 (7), 1378-1388 (2001)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,culture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,strain_SNP6

In [5]:
raw.shape

(221085, 95)

In [6]:
drop = ['pr2_accession', 'sequence_length', 'genbank_accession','organelle', 'added_version', 'edited_version', 'edited_by', 'edited_remark', 'remark', 'taxo_edited_version', 'taxo_edited_by',
        'taxo_remark', 'reference', 'mixoplankton', 'worms_id', 'worms_marine', 'worms_brackish', 'worms_freshwater', 'worms_terrestrial', 'sequence_hash',
       'gb_date', 'gb_division', 'gb_definition', 'gb_organism', 'gb_organelle', 'gb_strain', 'gb_culture_collection', 'gb_clone', 
       'gb_isolate', 'gb_isolation_source', 'gb_specimen_voucher', 'gb_host', 'gb_collection_date', 'gb_environmental_sample',
       'gb_country', 'gb_lat_lon', 'gb_collected_by', 'gb_note', 'gb_publication', 'gb_authors', 'gb_journal', 'eukref_name',
       'eukref_source', 'eukref_env_material', 'eukref_env_biome', 'eukref_biotic_relationship', 'eukref_specific_host',
       'eukref_geo_loc_name', 'eukref_notes', 'pr2_sample_type', 'pr2_sample_method', 'pr2_latitude', 'pr2_longitude', 'pr2_depth',
       'pr2_ocean', 'pr2_sea', 'pr2_sea_lat', 'pr2_sea_lon', 'pr2_country', 'pr2_location', 'pr2_location_geoname', 'pr2_location_geotype',
       'pr2_location_lat', 'pr2_location_lon', 'pr2_sequence_origin', 'metadata_remark', 'pr2_continent', 'pr2_country_geocode',
       'pr2_country_lat', 'pr2_country_lon', 'eukribo_UniEuk_taxonomy_string', 'eukribo_V4', 'eukribo_V9', 'organelle_code',
       'sequence_label']

raw.drop(columns=drop, inplace=True)

raw.shape

(221085, 20)

# Filtering

### Segment Type

In [7]:
raw = raw.loc[raw.gene == "18S_rRNA"]
raw.shape

(204386, 20)

### Sequence Position and Length

In [8]:
raw = raw.loc[raw.start == 1]
raw.shape

(196140, 20)

In [9]:
raw = raw.loc[raw.end >= 900]
raw.shape

(156818, 20)

# Format Rows

In [10]:
tax_levels = ["domain", "supergroup", "division", "subdivision", "class", "order", "family", "genus", "species"]

In [11]:
def format_row(row):

    # Remove invalid tax values
    for tax_level in tax_levels:    
        if str(row[tax_level]).endswith("_X") or str(row[tax_level]).endswith("_XX") or str(row[tax_level]).endswith("_XXX") or str(row[tax_level]).endswith("_sp."):
            row[tax_level] = pd.NA
    
    # Trunc sequence
    row["truncated_sequence"] = row["sequence"][0:900]

    return row


#raw.insert(9, "truncated_sequence", pd.NA)
raw = raw.apply(format_row, axis=1)
raw.shape

(156818, 21)

In [12]:
raw.head()

,domain,supergroup,division,subdivision,class,order,family,genus,species,start,end,label,gene,reference_sequence,taxo_id,seq_id,sequence,ambiguities,gb_taxonomy,silva_taxonomy,truncated_sequence
8159,Eukaryota,Amoebozoa,<NA>,<NA>,<NA>,UI13E03-lineage,<NA>,<NA>,<NA>,1,1543,U,18S_rRNA,1.0,2409,12004,GATAAGCCATGCAAATTTAAATTTAAGCCGGTTTCGGCGAAATTGT...,0,NaN,Eukaryota;Amorphea;Amoebozoa;Discosea;Flabelli...,GATAAGCCATGCAAATTTAAATTTAAGCCGGTTTCGGCGAAATTGT...
8160,Eukaryota,Amoebozoa,<NA>,<NA>,Lobosa-G1,<NA>,<NA>,<NA>,<NA>,1,1177,U,18S_rRNA,NaN,2890,8962,GTTAAAACTCGTAATCGGAGTGTTCGGATAGAGGATAAAATGAATT...,0,Eukaryota; Amoebozoa; unclassified Amoebozoa,Eukaryota;Amorphea;Amoebozoa;Discosea;Flabelli...,GTTAAAACTCGTAATCGGAGTGTTCGGATAGAGGATAAAATGAATT...
8161,Eukaryota,Amoebozoa,<NA>,<NA>,Lobosa-G1,<NA>,<NA>,<NA>,<NA>,1,1024,U,18S_rRNA,NaN,2890,69164,CCTTGGAATAGNATAGNTAGTACGTTTAGAAGCTCGTGATCGGAGT...,3,Eukaryota; Amoebozoa; unclassified Amoebozoa,Eukaryota;Amorphea;Amoebozoa;Discosea;Flabelli...,CCTTGGAATAGNATAGNTAGTACGTTTAGAAGCTCGTGATCGGAGT...
8162,Eukaryota,Amoebozoa,<NA>,<NA>,Lobosa-G1,<NA>,<NA>,<NA>,<NA>,1,1210,U,18S_rRNA,NaN,2890,144724,AGACAGTTAAAAAGCTCGTAGTCGGAGTTGTCCGGATAGAGGATAA...,6,Eukaryota; Amoebozoa; unclassified Amoebozoa,Eukaryota;Amorphea;Amoebozoa;Discosea;Flabelli...,AGACAGTTAAAAAGCTCGTAGTCGGAGTTGTCCGGATAGAGGATAA...
8163,Eukaryota,Amoebozoa,Discosea,<NA>,Centramoebia,Acanthopodida,Acanthamoebidae,Acanthamoeba,Acanthamoeba_astronyxis,1,2559,U,18S_rRNA,NaN,2834,68573,TCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAA...,0,Eukaryota; Amoebozoa; Discosea; Longamoebia; C...,Eukaryota;Amorphea;Amoebozoa;Discosea;Longamoe...,TCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAA...

# Save Cleaned Sequences File

In [13]:
raw.drop(columns=["sequence"])[raw["domain"].str.contains(":") == False].to_csv("./PR2/cleaned_sequences.csv", index=False)